apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
data:
  database_url: "jdbc:mysql://db.example.com:3306/mydatabase"
  database_user: "myuser"

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: database_url
    - name: DATABASE_USER
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: database_user
