apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  labels:
    app: xyz
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    
---

apiVersion: v1
kind: Namespace
metadata:
  name: development-ns
  labels:
    name: development
    tier: frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ns
  namespace: development-ns
  labels:
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80



