apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  nodeName: node01
  selector:
    matchLabels:
      app: deploy-1
  template:
    metadata:
      labels:
        app: deploy-1
    spec:
      containers:
      - name: deploy-container
        image: nginx
        ports:
        - containerPort: 80