apiVersion: v1
kind: Namespace
metadata:
  name: development-ns
  labels:
    name: development
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ns
  namespace: development-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80



