apiVersion: v1
kind: Namespace
metadata:
  name: development-ns
  labels:
    name: development
spec:
  selector:
    name: sam

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name : sam
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80


