apiVersion: v1
kind: Pod
metadata:
  name: httpd-server
  labels: 
    environment: local
  namespace: development-ns
spec:
  containers:
  - name: http-container
    image: httpd
    ports:
    - containerPort: 80

